baseurl = "https://www.codihuston.com/"
languageCode = "en-us"
title = "Codi's Blog"
theme = "codi-ng"
paginate = 2
Copyright = "© Codi Huston"
canonifyurls = true
assetDir = "static"

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = true
    startLevel = 2
  [markup.highlight]
    tabWidth = 2
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true

[params]
  author = "Codi Huston"
  aboutme = "I am a passionate software engineer with a passion for writing and sharing my knowledge with others! My focus is Web Development, DevOps, and cloud computing."
  description = "Welcome to my blog, where I discuss all things code, devlops, and tech."
  authorlocation = "Kentucky, USA"
  cover = "images/cover.png"
  ## save the image you want to use as background picture in directory "./static/images"author = "author name"(delete this line when editing)
  logo = "images/logo.png"
  ## save the image you want to use as website logo in directory "./static/images"(delete this line when editing)
  githubName = "codihuston"
  linkedinName = "codi-huston"
  email = "codi.huston@gmail.com"
  instagramName = "codihuston"
  paypal = "https://paypal.me/codihuston"
  hideHUGOSupport = false

[menu]
  [[menu.main]]
    name = "Home"
    pre = "house-blank"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "address-card"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    pre = "newspaper"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tags"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "Categories"
    pre = "layer-group"
    url = "/categories/"
    weight = 5

