baseurl = "https://www.codihuston.com/"
languageCode = "en-us"
title = "Codi's Blog"
theme = "codi-ng"
paginate = 2
Copyright = "© Codi Huston"
canonifyurls = true
assetDir = "static"

[params]
description = "Welcome to my blog, where I discuss all things code, devlops, and tech."
authorlocation = "Kentucky, USA"
cover = "images/cover.png"
## save the image you want to use as background picture in directory "./static/images"author = "author name"(delete this line when editing)
logo = "images/logo.png"
## save the image you want to use as website logo in directory "./static/images"(delete this line when editing)
githubName = "codihuston"
linkedinName = "codi-huston"
email = "codi.huston@gmail.com"
instagramName = "codihuston"
hideHUGOSupport = false

[menu]
  [[menu.main]]
    name = "Home"
    pre = "house-blank"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "newspaper"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Categories"
    pre = "layer-group"
    url = "/categories/"
    weight = 4

